name: main

concurrency:
  group: ${{ github.workflow }}

on:
  push:
    branches:
      - main

env:
  DISCORD_USERNAME: ${{ github.repository }}
  DISCORD_AVATAR: https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/gh-pages/img.png

jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "color": 16426275, "title": "deploying...", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }]'

  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 21.x
          extra_plugins: |
            @semantic-release/changelog@6.x
            @semantic-release/git@10.x
          branches: main
      - id: package-version
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - uses: peaceiris/actions-gh-pages@v4
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          allow_empty_commit: true

  notify-finished:
    if: ${{ success() || failure() }}
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@0.3.2
        if: ${{ success() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "color": 2357925, "title": "v${{ needs.release.outputs.version }} deployed", "url": "https://seleb.github.io/shuffled-deck" }]'
      - uses: Ilshidur/action-discord@0.3.2
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "color": 16393080, "title": "failed", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }]'
